import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by Hyunjung',
};

function Control() {
  return <ul></ul>;
}

export default async function RootLayout({ children }) {
  const res = await fetch('http://localhost:9999/topics', {
    cache: 'no-store',
  });
  const topics = await res.json();
  console.log('topics', topics);

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
